# Generated by Django 3.2.5 on 2021-07-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_alter_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='item',
        ),
        migrations.AddField(
            model_name='menu',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='menu',
            name='item_type',
            field=models.CharField(choices=[('DRINK', 'DRINK'), ('MEAL', 'MEAL'), ('DESERT', 'DESERT'), ('MAIN_DISH', 'MAIN_DISH')], default='MAIN_DISH', max_length=50),
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='testing name', max_length=50),
            preserve_default=False,
        ),
    ]
