# Generated by Django 3.2.5 on 2021-07-18 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_auto_20210718_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='c_date',
            field=models.DateField(default=datetime.date(2021, 7, 18)),
        ),
    ]
