# Generated by Django 3.2.5 on 2021-07-18 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_alter_menu_c_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='c_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboardrestaurant', to='menu_app.restaurant')),
            ],
        ),
    ]
